import { Plus_Jakarta_Sans } from 'next/font/google';
import React from 'react';

import './globals.css';
import { ToastContainer } from 'react-toastify';

import QueryClientProvider from '@/providers/query-client-provider';
import { ThemeProvider } from '@/providers/theme-provider';

import type { Metadata } from 'next';

const plus_jakarta_sans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${plus_jakarta_sans.variable} bg-background text-foreground antialiased`}
      >
        <QueryClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ToastContainer />
            {children}
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
